### ISSUE TITLE
Files listings are blank in Nextcloud-All-in-one 7.0.0 running Nextcloud 27.0.2

### ISSUE THREAD

**Issue by Bruceumba** [devnoname120/epubviewer#3] opened 2023-08-18 04:22 UTC
Nextcloud All-in-one v7.0.0 running Nextcloud v27.0.2.
When I enable the Epub viewer app v1.5.0 most of Nextcloud seems okay, but in the Files app I see no folder or files listings, and no control at the top showing me the directory I'm in nor the "+" circle for adding new items. When I disable the app everything returns to normal. I'm not running the Music app which is known to interfere with file deletion.

EDIT: Second issue: when enabled, I go into the user settings, click on "EPUB/CBZ/PDF ebook reader" and enable Epub and comics, but the settings never update anywhere. It gets stuck on "Saving ...". The checkboxes started unchecked.

**Comment by lightlike** [comment] 2023-08-20 15:45
Also happens with the [linuxserver.io docker](https://fleet.linuxserver.io/image?name=linuxserver/nextcloud). (`lscr.io/linuxserver/nextcloud:27.0.2`)
Exact same Error.

**Comment by EmJotGeh** [comment] 2023-08-21 20:34
Same here - blank folder page, no access to any folders and it's not possible to upload any files.

**Comment by c86-moe** [comment] 2023-08-24 13:04
Same here with traditional installation (install.php method) of NC27.

**Comment by me-cedric** [comment] 2023-08-28 04:24
Same issue here.

I am using NC27 (not the AIO version)

I cannot select file extensions in administration settings for the app.
Call sent returns a 500 error with the following log in NC.

This also causes the file list to be empty as long as the plugin is active.

Similar log as @jacksbox for the file list, this is the log for changing the selected file extentions : 
```
{
   "reqId":"V1Qzok2dntDOErnmK1QP",
   "level":3,
   "time":"2023-08-28T04:15:08+00:00",
   "remoteAddr":"176.180.183.60",
   "user":"mecedric",
   "app":"index",
   "method":"POST",
   "url":"/apps/epubviewer/settings/set",
   "message":"Autoload path not allowed: /var/www/html/custom_apps/epubviewer/lib/config.php",
   "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
   "version":"27.0.2.1",
   "exception":{
      "Exception":"OCP\\AutoloadNotAllowedException",
      "Message":"Autoload path not allowed: /var/www/html/custom_apps/epubviewer/lib/config.php",
      "Code":0,
      "Trace":[
         {
            "file":"/var/www/html/lib/autoloader.php",
            "line":166,
            "function":"isValidPath",
            "class":"OC\\Autoloader",
            "type":"->",
            "args":[
               "/var/www/html/custom_apps/epubviewer/lib/config.php"
            ]
         },
         {
            "file":"/var/www/html/custom_apps/epubviewer/lib/Controller/SettingsController.php",
            "line":58,
            "function":"load",
            "class":"OC\\Autoloader",
            "type":"->",
            "args":[
               "OCA\\Epubviewer\\Config"
            ]
         },
         {
            "file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
            "line":230,
            "function":"setPreference",
            "class":"OCA\\Epubviewer\\Controller\\SettingsController",
            "type":"->",
            "args":[
               "false",
               "false",
               "true"
            ]
         },
         {
            "file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
            "line":137,
            "function":"executeController",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->",
            "args":[
               [
                  "OCA\\Epubviewer\\Controller\\SettingsController"
               ],
               "setPreference"
            ]
         },
         {
            "file":"/var/www/html/lib/private/AppFramework/App.php",
            "line":183,
            "function":"dispatch",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->",
            "args":[
               [
                  "OCA\\Epubviewer\\Controller\\SettingsController"
               ],
               "setPreference"
            ]
         },
         {
            "file":"/var/www/html/lib/private/Route/Router.php",
            "line":315,
            "function":"main",
            "class":"OC\\AppFramework\\App",
            "type":"::",
            "args":[
               "OCA\\Epubviewer\\Controller\\SettingsController",
               "setPreference",
               [
                  "OC\\AppFramework\\DependencyInjection\\DIContainer"
               ],
               [
                  "epubviewer.settings.setPreference"
               ]
            ]
         },
         {
            "file":"/var/www/html/lib/base.php",
            "line":1071,
            "function":"match",
            "class":"OC\\Route\\Router",
            "type":"->",
            "args":[
               "/apps/epubviewer/settings/set"
            ]
         },
         {
            "file":"/var/www/html/index.php",
            "line":36,
            "function":"handleRequest",
            "class":"OC",
            "type":"::",
            "args":[
               
            ]
         }
      ],
      "File":"/var/www/html/lib/autoloader.php",
      "Line":141,
      "CustomMessage":"--"
   }
}
```

**Comment by otto-unnormalverbraucher** [comment] 2023-09-02 15:11
+1 
Similar behaviour here. 
I _can_ see the folders, if I click on newest files first and then click all files. Any **files** in the top level are accessible, but not the folders. 
I have group-folders enabled and can open the top level group-folders, but lower levels are inaccessible too.
Same log here as [jacksbox](https://github.com/jacksbox) reported.

**Comment by Bruceumba** [comment] 2023-09-03 18:02
+1 to Otto. I see no files until I go into the deleted files folder, and back to my main folder. Then I see the files and directories, and can access the files. But like Otto, I can't get into the directories. Alas, my pdf's still open in the pdf app, not the Epub Viewer. Settings still not settable.

**Comment by jdoss2020** [comment] 2023-09-04 00:08
Having the same issue as the others running 27.0.2 in docker.  When I install and enable the epub 1.5 app, I cannot see my files under the files tab.  If I bounce back and forth between the left hand menu options, I can eventually see the directories under Files, but clicking on the directories does nothing.  When I uninstall and remove the epub 1.5 app, the behavior under files returns to normal.  I would really love to have a working epub reader under nextcloud so I hope you can resolve this issue.

**Comment by jdoss2020** [comment] 2023-09-14 00:21
Any progress on this issue?

**Comment by devnoname120** [comment] 2023-09-15 01:59
Alright now that https://github.com/nextcloud/server/pull/40349 is merged I can do a fix without being impacted by another bug that would break NC 26 for existing users.

**Comment by devnoname120** [comment] 2023-09-15 02:32
I can't reproduce your issue neither on NextCloud `27.0.1` nor on NextCloud `27.0.2`. I'm using this Docker image: `ghcr.io/juliushaertl/nextcloud-dev-php82:latest` (see https://github.com/juliushaertl/nextcloud-docker-dev). I can't test the AIO Docker image easily because it requires me to set up a domain name or it refuses to work.

Which version of PHP are you using?

**Comment by Bruceumba** [comment] 2023-09-15 02:57
AIO uses 8.1.23 right now.
Version: 8.1.23

Memory limit: 536.9 MB

Max execution time: 3600

Upload max size: 10.7 GB

Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, readline, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, Phar, exif, gd, gmp, imagick, imap, intl, ldap, memcached, pcntl, pdo_pgsql, pgsql, redis, smbclient, sodium, sysvsem, zip, libsmbclient, Zend OPcache

**Comment by Bruceumba** [comment] 2023-09-15 03:20
Also happens on my bare install 27.0.2 and php8.1.

**Comment by devnoname120** [comment] 2023-09-15 04:16
Can you try this version and report back?
[epubviewer-b796a03.tar.gz](https://github.com/devnoname120/epubviewer/files/12615488/epubviewer-b796a03.tar.gz)

**Comment by whitehara** [comment] 2023-09-15 06:10
> Can you try this version and report back? [epubviewer-b796a03.tar.gz](https://github.com/devnoname120/epubviewer/files/12615488/epubviewer-b796a03.tar.gz)

I also met the same problem using with the nextcloud-docker, version 27.0.2.  And this version of the epubviewer works fine for me. Now I can see the files list. Thanks.

**Comment by EmJotGeh** [comment] 2023-09-15 14:03
The update 1.5.1 is not working - still no file list.

**Comment by devnoname120** [comment] 2023-09-15 14:55
@EmJotGeh update 1.5.1 is not meant to fix this issue it's unrelated. Can you try the file I posted just above?

**Comment by EmJotGeh** [comment] 2023-09-15 15:00
@devnoname120 Sorry, I was a bit hasty - yes, of course I can try that version.

**Comment by devnoname120** [comment] 2023-09-15 15:19
1) Can you try the latest NextCloud `master`? Can you delete and recreate your NextCloud containers? The issue may have been fixed in https://github.com/nextcloud/server/pull/40349

2) Can you paste the error log?

**Comment by EmJotGeh** [comment] 2023-09-15 15:23
I don't use docker - this is a native install.

**Comment by devnoname120** [comment] 2023-09-15 15:24
Can you use the latest NextCloud `master` branch anyway?

**Comment by EmJotGeh** [comment] 2023-09-15 15:28
sorry, i can only wait for the NC Update 27.1.0 and then I could try it again.

**Comment by devnoname120** [comment] 2023-09-15 16:12
I think I'll use a custom autoloader in the future because I don't trust NextCloud devs not to break it again. It's a pain to maintain a NextCloud app they keep introducing changes and bugs in every new version.

**Comment by devnoname120** [comment] 2023-09-16 15:27
@Bruceumba @jacksbox @lightlike @EmJotGeh @me-cedric @otto-unnormalverbraucher @c86-moe Can you try this version and report back?
[epubviewer-b796a03.tar.gz](https://github.com/devnoname120/epubviewer/files/12615488/epubviewer-b796a03.tar.gz)

**Comment by EmJotGeh** [comment] 2023-09-16 17:23
It looks like the app works with 27.1.0. Maybe someone else can verify this too.

**Comment by Bruceumba** [comment] 2023-09-16 22:32
epubviewer v1.5.1 on Nextcloud AIO 27.1.0  had blank file listings still.

**Comment by EmJotGeh** [comment] 2023-09-16 22:34
@Bruceumba did you try the package above?

**Comment by devnoname120** [comment] 2023-09-16 22:35
Use the version I posted not 1.5.1.

**Comment by c86-moe** [comment] 2023-09-16 22:38
Hi @devnoname120 

I can confirm the b796a03 package would resolve this issue on Nextcloud 27.1.0 (PHP direct installation).

PHP 8.2, with LiteSpeed Enterprise.

Thanks for providing this package.

**Comment by devnoname120** [comment] 2023-09-18 00:31
Fixed in https://github.com/devnoname120/epubviewer/commit/67de054a88ea0582bcd19cf6f1ae14ea1a403fff and https://github.com/devnoname120/epubviewer/commit/22116fd4cb8cf9235726b8b53d204d8281e10f45.
See version `1.5.2` from the [releases page](https://github.com/devnoname120/epubviewer/releases).

**Closed** 2023-09-18 00:31 UTC
